# Generated by Django 3.1.7 on 2021-03-11 07:54

import app.models
import datetime
from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Телефон')),
                ('fathername', models.CharField(blank=True, max_length=150, null=True, verbose_name='Отчество')),
                ('gender', models.IntegerField(choices=[(0, 'None'), (1, 'Male'), (2, 'Female')], default=0, verbose_name='Пол')),
                ('birth_date', models.DateField(blank=True, default=datetime.date.today, verbose_name='Дата рождение')),
                ('card', models.CharField(blank=True, max_length=16, null=True, verbose_name='Банковская карта')),
                ('country', models.CharField(default='Казахстан', max_length=20, null=True, verbose_name='Страна')),
                ('lead_activity', models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Активность лида')),
                ('client_activity', models.DateTimeField(blank=True, null=True, verbose_name='Активность клиента')),
                ('is_online', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='Название')),
                ('cost', models.IntegerField(default=0, help_text='в тенге', verbose_name='Стоимость')),
                ('poster', models.FileField(blank=True, null=True, upload_to=app.models.content_file_name_courses, verbose_name='Постер')),
                ('mini_poster', models.FileField(blank=True, null=True, upload_to=app.models.content_file_name_courses, verbose_name='Мини Постер')),
                ('short_desc', models.TextField(blank=True, max_length=200, null=True, verbose_name='Короткое описание')),
                ('full_desc', models.TextField(blank=True, max_length=500, null=True, verbose_name='Полное описание')),
                ('lesson_count', models.IntegerField(blank=True, default=0, null=True, verbose_name='Количество уроков')),
                ('start_date', models.DateField(default=datetime.date.today, verbose_name='Начало даты')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Конец даты')),
                ('duration', models.IntegerField(blank=True, default=0, help_text='в минутах', null=True, verbose_name='Длителность')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публикации')),
                ('creator_id', models.ForeignKey(blank=True, help_text='Создатель курса', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
            },
        ),
        migrations.CreateModel(
            name='Vector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='Название')),
                ('short_desc', models.TextField(blank=True, max_length=200, null=True, verbose_name='Короткое описание')),
                ('pub_date', models.DateField(blank=True, default=datetime.date.today, verbose_name='Дата публикации')),
                ('course_count', models.IntegerField(blank=True, default=0, null=True, verbose_name='Количество курсов')),
                ('duration', models.IntegerField(blank=True, default=0, help_text='в минутах', null=True, verbose_name='Длителность')),
                ('creator_id', models.ForeignKey(blank=True, help_text='Создатель курса', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Направление',
                'verbose_name_plural': 'Направлении',
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Школа')),
                ('sub_domen', models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Домен')),
                ('school_logo_1', models.FileField(blank=True, null=True, upload_to=app.models.content_file_name_logo, verbose_name='Лого 250x64')),
                ('school_logo_2', models.FileField(blank=True, null=True, upload_to=app.models.content_file_name_logo, verbose_name='Лого 16x16')),
                ('creator_id', models.ForeignKey(blank=True, help_text='Создатель школы', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Школа',
                'verbose_name_plural': 'Школы',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='Название')),
                ('short_desc', models.TextField(blank=True, max_length=200, null=True, verbose_name='Короткое описание')),
                ('full_desc', models.TextField(blank=True, max_length=500, null=True, verbose_name='Полное описание')),
                ('files', models.FileField(blank=True, null=True, upload_to='lessons', verbose_name='Содержание урока')),
                ('video', models.FileField(blank=True, null=True, upload_to='lessons', verbose_name='Содержание урока')),
                ('duration', models.IntegerField(blank=True, default=0, help_text='в минутах', null=True, verbose_name='Длителность')),
                ('pub_date', models.DateField(blank=True, default=datetime.date.today, verbose_name='Дата публикации')),
                ('course_id', models.ForeignKey(blank=True, help_text='курс', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.course')),
                ('teacher_id', models.ForeignKey(blank=True, help_text='Учитель курса', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
            },
        ),
        migrations.CreateModel(
            name='KnowledgeBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.FileField(blank=True, null=True, upload_to=app.models.content_file_name_knowledge, verbose_name='Файлы')),
                ('pub_date', models.DateField(blank=True, default=datetime.date.today, verbose_name='Дата публикации')),
                ('course_id', models.ForeignKey(blank=True, help_text='курс', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.course')),
                ('lesson_id', models.ForeignKey(blank=True, help_text='урок', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.lesson')),
            ],
            options={
                'verbose_name': 'База Знании',
                'verbose_name_plural': 'Базы Знании',
            },
        ),
        migrations.CreateModel(
            name='HomeWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='Название')),
                ('desc', models.TextField(blank=True, max_length=5000, null=True, verbose_name='Короткое описание')),
                ('files', models.FileField(blank=True, null=True, upload_to=app.models.content_file_name_hw, verbose_name='Содержание ДЗ')),
                ('pub_date', models.DateField(blank=True, default=datetime.date.today, verbose_name='Дата публикации')),
                ('checked', models.BooleanField(blank=True, default=False, null=True, verbose_name='Проверено?')),
                ('grade', models.CharField(blank=True, default='0/0', max_length=10, null=True, verbose_name='Оценка')),
                ('course_id', models.ForeignKey(blank=True, help_text='курс', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.course')),
                ('lesson_id', models.ForeignKey(blank=True, help_text='урок', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.lesson')),
                ('student_id', models.ForeignKey(blank=True, help_text='Ученик курса', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Домашнее Задание',
                'verbose_name_plural': 'Домашние Задании',
            },
        ),
        migrations.CreateModel(
            name='Exercise_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='Название задании')),
                ('pub_date', models.DateField(blank=True, default=datetime.date.today, verbose_name='Дата публикации')),
                ('files', models.FileField(blank=True, null=True, upload_to=app.models.content_file_name_ex_list, verbose_name='Файлы')),
                ('creator_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('lesson_id', models.ForeignKey(blank=True, help_text='урок', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.lesson')),
            ],
            options={
                'verbose_name': 'Список Задач',
                'verbose_name_plural': 'Списки Задач',
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='Название шаблона')),
                ('desc', models.TextField(blank=True, max_length=200, null=True, verbose_name='Условие упражнение')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст для упражнения')),
                ('files', models.FileField(blank=True, null=True, upload_to=app.models.content_file_name_ex, verbose_name='Содержание ДЗ')),
                ('creator_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ex_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.exercise_list')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
            },
        ),
        migrations.CreateModel(
            name='Course_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=datetime.date.today, verbose_name='Начало даты')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Конец даты')),
                ('activity', models.DateTimeField(blank=True, null=True, verbose_name='Активность клиента')),
                ('course_id', models.ForeignKey(blank=True, help_text='курс', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.course')),
                ('student_id', models.ForeignKey(blank=True, help_text='Ученик курса', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Доступ к Курсу',
                'verbose_name_plural': 'Доступы к Курсам',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='vector_id',
            field=models.ForeignKey(blank=True, help_text='Направление', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.vector'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публикации')),
                ('change_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата изменении')),
                ('content', models.CharField(blank=True, max_length=220, null=True, verbose_name='Контент')),
                ('course_id', models.ForeignKey(blank=True, help_text='Курс', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.course')),
                ('user_id', models.ForeignKey(blank=True, help_text='Комментатор', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='school_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.school', verbose_name='Школа'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
