# Generated by Django 3.1.7 on 2021-03-11 08:27

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_user_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', app.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='course',
            name='full_desc',
            field=models.TextField(blank=True, max_length=5000, null=True, verbose_name='Полное описание'),
        ),
        migrations.AlterField(
            model_name='course',
            name='short_desc',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Короткое описание'),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='title',
            field=models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='full_desc',
            field=models.TextField(blank=True, max_length=5000, null=True, verbose_name='Полное описание'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='short_desc',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Короткое описание'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='vector',
            name='short_desc',
            field=models.TextField(blank=True, max_length=800, null=True, verbose_name='Короткое описание'),
        ),
        migrations.AlterField(
            model_name='vector',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Название'),
        ),
    ]
