# Generated by Django 3.1.7 on 2021-03-15 08:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210311_1659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='creator_id',
        ),
        migrations.AddField(
            model_name='course',
            name='teacher_id',
            field=models.ManyToManyField(blank=True, help_text='Создатель курса', null=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='course',
            name='vector_id',
        ),
        migrations.AddField(
            model_name='course',
            name='vector_id',
            field=models.ManyToManyField(blank=True, help_text='Направление', null=True, to='app.Vector'),
        ),
    ]
