# Generated by Django 3.1.7 on 2021-03-15 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20210315_1502'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='knowledgebase',
            name='course_id',
        ),
        migrations.RemoveField(
            model_name='knowledgebase',
            name='lesson_id',
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Название файла'),
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='type_id',
            field=models.IntegerField(blank=True, help_text='урок', null=True, verbose_name='ID для файла'),
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='type_name',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'Курс'), (2, 'Урок'), (3, 'Лист Задач'), (4, 'Задача'), (5, 'ДЗ')], default=0, verbose_name='Тип для файла'),
        ),
    ]
