# Generated by Django 3.1.7 on 2021-03-16 05:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20210315_1644'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='files',
        ),
        migrations.RemoveField(
            model_name='exercise_list',
            name='files',
        ),
        migrations.RemoveField(
            model_name='homework',
            name='files',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='files',
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='creator_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='knowledgebase',
            name='type_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID для файла'),
        ),
        migrations.AlterField(
            model_name='knowledgebase',
            name='type_name',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'Урок'), (2, 'Лист Задач'), (3, 'Задача'), (4, 'ДЗ')], default=0, verbose_name='Тип для файла'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'Мужчина'), (2, 'Женщина')], default=0, verbose_name='Пол'),
        ),
    ]
